Repository KangHayeonn/pick-movie, pull requests merged in 2022-10, with the labels that each got.

#30 [add]: 프로젝트 폴더 & 라우터 구성
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/plugins/tokenControl.js
  front/src/routes/index.js
  front/src/views/account/LoginPage.vue
  front/src/views/account/SignupPage.vue
  front/src/views/cart/CartPage.vue
  front/src/views/main/MainPage.vue
  front/src/views/posts/PostsPage.vue
  front/src/views/profile/ProfilePage.vue
  front/src/views/search/SearchPage.vue
Labels: ✨ add

#31 [add]: store 초기 환경 세팅 & signup 기능 구현
  front/package.json
  front/src/api/index.js
  front/src/components/account/LoginForm.vue
  front/src/components/account/SignupForm.vue
  front/src/components/account/scss/style.scss
  front/src/main.js
  front/src/store/index.js
  front/src/store/modules/auth.js
  front/src/store/modules/index.js
  front/src/utils/validation.js
Labels: 🌱 wip, ✨ add, 🌈 update

#26 [add] : movieController 추가
  .DS_Store
  back/.DS_Store
  back/.gitignore
  back/src/main/java/com/pick/movie/back/controller/MovieController.java
  back/src/main/java/com/pick/movie/back/controller/loginController.java
  back/src/main/java/com/pick/movie/back/dto/LikeListRequestDto.java
  back/src/main/java/com/pick/movie/back/dto/LikeListResponseDto.java
  back/src/main/java/com/pick/movie/back/dto/LoginRequestDto.java
  back/src/main/java/com/pick/movie/back/dto/MovieInfoDto.java
  back/src/main/java/com/pick/movie/back/dto/SignupDto.java
  back/src/main/java/com/pick/movie/back/repository/LikeListRepository.java
  back/src/main/java/com/pick/movie/back/repository/MovieInfoRepository.java
Labels: ✨ add, ✋ code-review

#32 [refactor] : .DS_Store delete
  back/.DS_Store
Labels: ♻ refactor

#33 [add]: 회원가입 validation 기능 및 예외처리 구현
  front/src/api/index.js
  front/src/components/account/LoginForm.vue
  front/src/components/account/SignupForm.vue
  front/src/utils/validation.js
Labels: ✨ add, 🌈 update

#34 [update] : validation.js - escape eslint 에러 삭제
  front/src/utils/validation.js
Labels: 😱 issue, 🍞 test, 🌈 update

#35 Feature/hayeon
  front/src/api/common/interceptors.js
  front/src/api/index.js
  front/src/api/v1Auth.js
  front/src/api/v1Movie.js
  front/src/components/account/LoginForm.vue
  front/src/components/account/SignupForm.vue
  front/src/components/account/scss/style.scss
  front/src/layouts/Container.vue
  front/src/layouts/Header.vue
  front/src/plugins/tokenControl.js
  front/src/store/modules/auth.js
  front/src/views/main/MainPage.vue
Labels: ✨ add, ♻ refactor, 🌈 update
